---
Name: silverstripe-robots
---

suppress: warning

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - RobotsSiteConfigExtension

SilverStripe\Control\Director:
  rules:
    'robots.txt': 'RobotsController'